### ISSUE TITLE
Error in names(mm3) <- nms :    'names' attribute [31] must be the same length as the vector [27]

### ISSUE THREAD

**Issue by Fabiola-Eto** [hputter/mstate#25] opened 2023-09-15 15:39 UTC
I'm running a `mstate` model with a 17-by-17 transition matrix. The matrix makes sense and the numbers of events (frequencies and percentages) are correct. I ran the `msprep()` function smoothly  as well. The issue I get stuck with is when I try to run the function `expand.covs()`. This error message pops out: 

```
Error in names(mm3) <- nms : 
  'names' attribute [31] must be the same length as the vector [27]
```
I checked that my data is an object of class `msdata` as required. The covariates have no missing data, and their length is the same length as the `mstata` object. I tried different types of covariates (integer, numeric, factor), but the error message persisted regardless. I couldn't find a similar error for users of the `mstate` package, nor could find a possible explanation in the vignette. 

I appreciate it if you could help me find the cause of the error. Thanks.

**Comment by edbonneville** [comment] 2024-06-12 15:54
@Fabiola-Eto (apologies for delay in responding to this) were you able to find the solution to your problem? If not, could you please try to prepare a [minimal reproducible example](https://reprex.tidyverse.org/) ? Thanks!

**Comment by edbonneville** [comment] 2024-06-23 09:36
Will close this issue since no reproducible example given, but please do re-open if you run into something similar again.

**Closed by edbonneville** 2024-06-23 09:36 UTC
